apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: confidential-cluster-operator-dev-preview
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-operator-index:v4.21-confidential-cluster-operator-dev-preview-1776328780
  displayName: "Confidential Cluster Operator (Dev Preview)"
  publisher: "Red Hat (Dev)"
