apiVersion: trusted-execution-clusters.io/v1alpha1
kind: TrustedExecutionCluster
metadata:
  name: confidential-cluster
  namespace: confidential-clusters
spec:
  publicTrusteeAddr: kbs-service-confidential-clusters.<DOMAIN>
  registerServerPort: 8000
  trusteeKbsPort: 8080
