apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: confidential-clusters-og
  namespace: confidential-clusters
spec:
  targetNamespaces:
    - confidential-clusters
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: confidential-clusters-sub
  namespace: confidential-clusters
spec:
  channel: dev-preview
  name: confidential-cluster-operator
  source: confidential-cluster-operator-dev-preview
  sourceNamespace: openshift-marketplace
